# Generated by Django 5.0.1 on 2024-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Location', models.CharField(max_length=200)),
                ('Registration', models.CharField(max_length=225)),
                ('Requirement', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
