# Generated by Django 5.0.1 on 2024-01-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fssiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='PhoneNumber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Registration',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Requirement',
            new_name='requirement',
        ),
    ]
