# Generated by Django 5.0.1 on 2024-01-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fssiapp', '0002_rename_email_enquiry_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
