# Generated by Django 5.0.1 on 2024-01-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fssiapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
