# Generated by Django 5.0.1 on 2024-02-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssiapp', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadedEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssiapp.enquiry')),
            ],
        ),
    ]
