# Generated by Django 5.0.1 on 2024-02-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssiapp', '0008_rename_readedenquiry_openedenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedenquiry',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssiapp.enquiry', unique=True),
        ),
    ]
