# Generated by Django 5.0.1 on 2024-02-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssiapp', '0009_alter_openedenquiry_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedenquiry',
            name='enquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fssiapp.enquiry'),
        ),
    ]
