# Generated by Django 5.0.1 on 2024-02-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fssiapp', '0010_alter_openedenquiry_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openedenquiry',
            old_name='enquiry',
            new_name='enquiry_id',
        ),
    ]
