# Generated by Django 5.0.1 on 2024-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssiapp', '0011_rename_enquiry_openedenquiry_enquiry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OpenedEnquiry',
        ),
    ]
